org: danielnota
app: events-monitoring
service: events-monitoring

provider:
  name: aws
  runtime: nodejs12.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "*"
custom:
  url_infura: ${env:URL_INFURA}
  url_redis: ${env:URL_REDIS}
  url_dynamodb: ${env:URL_DYNAMODB}
  dev: ${env:DEV}

package:
  # individually: true
  include:
    - node_modules
    - src/utils

functions:
  watchlogsfromethereum:
    handler: src/WatchLogsFromEthereum/handler.watch
    package:
      include:
        - src/WatchLogsFromEthereum/logswatcher.ts
    environment:
      - URL_INFURA: ${self:custom.url_infura}
      - DEV: ${self:custom.dev}
  filterevents:
    handler: src/FilterEvents/handler.filter
    environment:
      - URL_REDIS: ${self:custom.url_redis}
      - DEV: ${self:custom.dev}
  checkconditions:
    handler: src/CheckConditions/handler.check
    environment:
      - URL_REDIS: ${self:custom.url_redis}
      - URL_DYNAMODB: ${self:custom.url_dynamodb}
      - DEV: ${self:custom.dev}
  unsubscribeemailbytoken:
    handler: src/UnsubscribeEmailByToken/handler.unsubscribe
    events:
      - http:
          path: email/unsubscribe/{email}/{token}
          method: get
          request:
            parameters:
              paths:
                token: true
                email: true
  validateemailbytoken:
    handler: src/ValidateEmailByToken/handler.validate
    events:
      - http:
          path: email/validate/{email}/{token}
          method: get
          request:
            parameters:
              paths:
                token: true
                email: true
  createnewwatch:
    handler: src/CreateNewWatch/handler.create
    events:
      - http:
          path: watch
          method: post
plugins:
  - serverless-plugin-typescript
  - serverless-offline-scheduler
  - serverless-offline
resources:
  Resources:
    WatchersDynamoDbTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: "email"
            AttributeType: "S"
          - AttributeName: "id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "email"
            KeyType: "HASH"
          - AttributeName: "id"
            KeyType: "RANGE"
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        StreamSpecification:
          StreamViewType: "NEW_AND_OLD_IMAGES"
        TableName: "Watcher"
    HistoricDynamoDbTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        StreamSpecification:
          StreamViewType: "KEYS_ONLY"
        TableName: "Historic"
