org: danielnota
app: events-monitoring
service: events-monitoring

provider:
  name: aws
  region: eu-central-1
  runtime: nodejs12.x
  vpc:
    securityGroupIds:
      - sg-0b619b76
    subnetIds:
      - subnet-b44985c8
      - subnet-d44b9898
      - subnet-e273e288
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - lambda:InvokeAsync
      Resource: "*"
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "*"
    - Effect: Allow
      Action:
        - elasticache:*
      Resource: "*"
custom:
  url_infura: ${env:URL_INFURA}
  url_redis: ${env:URL_REDIS}
  url_dynamodb: ${env:URL_DYNAMODB}

package:
  # individually: true
  include:
    - src/utils

functions:
  watchlogs:
    handler: src/WatchLogsFromEthereum/handler.watch
    timeout: 240
    events:
      - schedule:
          rate: rate(1 minute)
          enabled: true
    package:
      include:
        - src/WatchLogsFromEthereum/logswatcher.ts
    environment:
      URL_INFURA: ${self:custom.url_infura}
  filterevents:
    handler: src/FilterEvents/handler.filter
    environment:
      URL_REDIS: ${self:custom.url_redis}
  checkconditions:
    handler: src/CheckConditions/handler.check
    environment:
      URL_REDIS: ${self:custom.url_redis}
  unsubscribeemailbytoken:
    handler: src/UnsubscribeEmailByToken/handler.unsubscribe
    events:
      - http:
          path: email/unsubscribe/{email}/{token}
          method: get
          request:
            parameters:
              paths:
                token: true
                email: true
  validateemailbytoken:
    handler: src/ValidateEmailByToken/handler.validate
    events:
      - http:
          path: email/validate/{email}/{token}
          method: get
          request:
            parameters:
              paths:
                token: true
                email: true
  createnewwatch:
    handler: src/CreateNewWatch/handler.create
    events:
      - http:
          path: watch
          method: post
  sendemailbytopic:
    handler: src/SendEmailByTopic/handler.send
    events:
      - stream: arn:aws:dynamodb:eu-central-1:351020644073:table/Watcher/stream/2020-09-24T12:50:34.957
      - stream: arn:aws:dynamodb:eu-central-1:351020644073:table/Historic/stream/2020-09-24T15:40:34.587
  updatecounterstatus:
    handler: src/UpdateCounterStatus/handler.update
    events:
      - stream: arn:aws:dynamodb:eu-central-1:351020644073:table/Watcher/stream/2020-09-24T12:50:34.957

plugins:
  - serverless-plugin-typescript
  - serverless-offline-scheduler
  - serverless-offline
resources:
  Resources:
    WatchersDynamoDbTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: "email"
            AttributeType: "S"
          - AttributeName: "id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "email"
            KeyType: "HASH"
          - AttributeName: "id"
            KeyType: "RANGE"
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        StreamSpecification:
          StreamViewType: "NEW_AND_OLD_IMAGES"
        TableName: "Watcher"
    HistoricDynamoDbTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        StreamSpecification:
          StreamViewType: "NEW_IMAGE"
        TableName: "Historic"
