org: danielnota
app: events-monitoring
service: events-monitoring

provider:
  name: aws
  runtime: nodejs12.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "*"
custom:
  url_infura: ${env:URL_INFURA}
  url_redis: ${env:URL_REDIS}
  url_dynamodb: ${env:URL_DYNAMODB}
  dev: ${env:DEV}

package:
  # individually: true
  include:
    - node_modules
    - src/utils
    - src/types

functions:
  watchlogsfromethereum:
    handler: src/WatchLogsFromEthereum/handler.watch
    package:
      include:
        - src/WatchLogsFromEthereum/logswatcher.ts
    events:
      - schedule:
          rate: rate(1 minute)
          enabled: true
    environment:
      - URL_INFURA: ${self:custom.url_infura}
      - DEV: ${self:custom.dev}
  filterevents:
    handler: src/FilterEvents/handler.filter
    environment:
      - URL_REDIS: ${self:custom.url_redis}
      - DEV: ${self:custom.dev}
  checkconditions:
    handler: src/CheckConditions/handler.check
    environment:
      - URL_REDIS: ${self:custom.url_redis}
      - URL_DYNAMODB: ${self:custom.url_dynamodb}
      - DEV: ${self:custom.dev}
plugins:
  - serverless-plugin-typescript
  - serverless-offline-scheduler
  - serverless-offline
resources:
  Resources:
    WatchersDynamoDbTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
          - AttributeName: "email"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
          - AttributeName: "email"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: "NEW_IMAGE"
        TableName: "Watchers"
    HistoricDynamoDbTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: "KEYS_ONLY"
        TableName: "Historic"
